# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Stay.create!(name:"Tulum's Rocks", location: "Mexico", description: "Tulum Rock's close to whatever you will need just like restaurants, bars & markets. All rooms have air conditioning, fan, private lockers and new mattresses.", url_to_image: "")
Stay.create!(name:"Rocking J’s", location: "Costa Rica", description: "Rocking Js is sort of an institution in Central America. It’s been there for ages, there’s a beautiful white sand beach in front of it, they serve decent food and have nightly BBQs, and there’s lots of partying. Moreover, they have a wide variety of cheap accommodation (from hammocks to private rooms).")
Stay.create!(name:"Franceso’s", location: "Greece", description: "It’s impossible not to meet people here. Plus, there’s a pool. Francesco’s is also next to the most wonderful milkshake-making place on the entire planet. The rooms are quite nice and the beds comfy, but what really makes this place so wonderful is its central location and the fact you make tons of new friends every night.")
Stay.create!(name:"Kabul", location: "Spain", description: "Arguably one of the best hostels in the world, Kabul is just an all-out fun-filled place, but only if you are looking to spend your nights partying. You don’t come to Kabul to sleep. It is so well known for its atmosphere and parties that it’s always fully booked, and during the summer, it’s booked months in advance. Everyone socializes in the halls and dorms, getting to know other travelers, playing card games, drinking, and listening to music, or heads downstairs to the giant common room to enjoy dirt-cheap beer and pool. ")
Stay.create!(name:"Nomads", location: "New Zealand", description: "The hostel has a huge kitchen (restaurant sized), top-notch showers (with great water pressure) and toilets, and a large lounge, and most rooms have balconies. ")
Stay.create!(name:"The Flying Pig", location: "The Netherlands", description: "The facilities here are standard (except the pillows, which are like sleeping on air), and the prices are on the expensive side, but I love the atmosphere here. While this hostel is popular with travelers looking to chill and smoke weed, the bar area gets very busy at night with those who don’t. It’s not all about smoking here. ")
Stay.create!(name:"Base St. Kilda", location: "Australia", description: "The bar is lively every night, and there are BBQs and events during the week. Moreover, the rooms and bathrooms are clean and very well maintained. Most people stay here for the atmosphere and location. ")
Stay.create!(name:"Hostel Mostel", location: "Bulgaria", description: "This hostel has locations in two cities in Bulgaria (Sofia and Veliko Tarnovo), and they all follow the same principles: comfy beds, free breakfast, free dinner, free beer, fee shots, a pool table, and free, fast Wi-Fi. And you know, it’s hard not to like a place that gives you a delicious breakfast, free beer, and pasta each night. ")
Stay.create!(name:"Tallinn Backpackers", location: "Estonia", description: "The beds here are soft, and I probably got the best night’s sleep here that I’d had in a while. And it’s not loud at night because everyone is out, and they shut down the common area at midnight so people can sleep. ")
Stay.create!(name:"Green Tortoise", location: "Washington", description: "They offer a robust breakfast, run lots of activities and events for people who stay there, have friendly staff, and comfy beds. They are really solid places that combine the best of the hostel spirit.")
Stay.create!(name:"Naked Tiger", location: "Nicaragua", description: "Located in the beautiful beach town of San Juan del Sur, the Naked Tiger is an incredible property nestled a bit far out of town but on top of a hill with a beautiful view of the entire area. Here you’ll find a party like atmosphere as the staff wants everyone to have a great time! ")
Stay.create!(name:"Gallery Hostel", location: "Porto", description: "his “luxury” hostel in Porto, Portugal is not the cheapest in Porto, but this hostel/art gallery features home-cooked Portuguese food, a backyard, free after-dinner drinks, a game room, and friendly staff committed to making sure everyone gets to know each other. ")
Stay.create!(name:"City Backpackers", location: "Stockholm", description: "Their beds and pillows are still super cozy and comfortable, plus they have a huge kitchen, common room, free sauna, and laundry facilities. And you can’t turn a corner without bumping into a public computer. City Backpackers was and still is one of the top hostels in Europe.")
Stay.create!(name:"Khaosan Hostel", location: "Tokyo", description: "This awesome hostel chain in Tokyo features comfy beds and soft pillows, a warm and knowledgeable staff, and very central locations. Like everything else in Japan, the facilities are spotless, there’s free tea and coffee, and lovely outdoor spaces and common areas to just chill out in.")
Stay.create!(name:"Milhouse", location: "Buenos Aires", description: "This amazing hostel in Buenos Aires offers free coffee and tea, paid breakfast has an awesome ba and rooftop, a kitchen, free lockers, a pool table, and board games. Not only that, they host amazing dinners on said rooftop and at night this place becomes a wild party.")
Stay.create!(name:"Fabrika", location: "Tbilisi", description: "Outside the courtyard, you’ll find an array of bars and restaurants. The dorms are very spacious with soft beds and your own light and electric outlet. This multi-use space is also extremely popular with locals and is one of the hip places to be in the city.")
Stay.create!(name:"HK Austin", location: "Austin", description: "From the new mattresses to the spacious dorms to the comfy common room couches to the BBQs they throw, this place really knows how to make you feel at home.")
Stay.create!(name:"The B.I.G Backpackers", location: "Cape Town", description: "For sure solo travellers of every kind will love the friendly ambience and home-from-home social spaces.")
